apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: stock-bind
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: stock-controller
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: stock-producer